/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao2;

import br.com.controle.Questoes;

/**
 *
 * @author laboratorio
 */
public class Tela2 extends javax.swing.JFrame {
    Questoes q = new Questoes();
    /**
     * Creates new form Tela2
     */
    public Tela2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGquestao1 = new javax.swing.ButtonGroup();
        bGquestao2 = new javax.swing.ButtonGroup();
        bGquestao3 = new javax.swing.ButtonGroup();
        bGquestao4 = new javax.swing.ButtonGroup();
        bGquestao5 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPquestao1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRq1a = new javax.swing.JRadioButton();
        jRq1b = new javax.swing.JRadioButton();
        jRq1c = new javax.swing.JRadioButton();
        jRcorreta1 = new javax.swing.JRadioButton();
        jRq1e = new javax.swing.JRadioButton();
        jPquestao2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRcorreta2 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jPquestao3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRcorreta3 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jPquestao4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRcorreta4 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jPquestao5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRcorreta5 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jBenviar = new javax.swing.JButton();
        jLresultadopontos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPquestao1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("1. Quais são as cores primárias?");

        bGquestao1.add(jRq1a);
        jRq1a.setText("Vermelho, azul, verde");

        bGquestao1.add(jRq1b);
        jRq1b.setText("Azul, roxo, verde");

        bGquestao1.add(jRq1c);
        jRq1c.setText("Verde, amarelo, azul");

        bGquestao1.add(jRcorreta1);
        jRcorreta1.setText("Vermelho, azul, amarelo");

        bGquestao1.add(jRq1e);
        jRq1e.setText("Amarelo, laranja, azul");

        javax.swing.GroupLayout jPquestao1Layout = new javax.swing.GroupLayout(jPquestao1);
        jPquestao1.setLayout(jPquestao1Layout);
        jPquestao1Layout.setHorizontalGroup(
            jPquestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPquestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRq1a)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRq1b)
                    .addComponent(jRq1c)
                    .addComponent(jRcorreta1)
                    .addComponent(jRq1e))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPquestao1Layout.setVerticalGroup(
            jPquestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRq1a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRq1b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRq1c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRcorreta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRq1e)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPquestao2.setBackground(new java.awt.Color(178, 178, 178));

        jLabel2.setText("2. Qual desses animais é conhecido como o \"melhor amigo do homem\"? ");

        bGquestao2.add(jRadioButton6);
        jRadioButton6.setText("Gato");

        bGquestao2.add(jRadioButton7);
        jRadioButton7.setText("Cavalo");

        bGquestao2.add(jRcorreta2);
        jRcorreta2.setText("Cachorro");

        bGquestao2.add(jRadioButton9);
        jRadioButton9.setText("Pássaro");

        bGquestao2.add(jRadioButton10);
        jRadioButton10.setText("Coelho");

        javax.swing.GroupLayout jPquestao2Layout = new javax.swing.GroupLayout(jPquestao2);
        jPquestao2.setLayout(jPquestao2Layout);
        jPquestao2Layout.setHorizontalGroup(
            jPquestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPquestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRcorreta2)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPquestao2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );
        jPquestao2Layout.setVerticalGroup(
            jPquestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRcorreta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPquestao3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("3. Qual é o maior planeta do nosso sistema solar? ");

        bGquestao3.add(jRadioButton11);
        jRadioButton11.setText("Terra");

        bGquestao3.add(jRadioButton12);
        jRadioButton12.setText("Marte");

        bGquestao3.add(jRcorreta3);
        jRcorreta3.setText("Júpiter");

        bGquestao3.add(jRadioButton14);
        jRadioButton14.setText("Saturno");

        bGquestao3.add(jRadioButton15);
        jRadioButton15.setText("Vênus");

        javax.swing.GroupLayout jPquestao3Layout = new javax.swing.GroupLayout(jPquestao3);
        jPquestao3.setLayout(jPquestao3Layout);
        jPquestao3Layout.setHorizontalGroup(
            jPquestao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPquestao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton11)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton12)
                    .addComponent(jRcorreta3)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPquestao3Layout.setVerticalGroup(
            jPquestao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRcorreta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPquestao4.setBackground(new java.awt.Color(178, 178, 178));

        jLabel4.setText("4. Qual desses alimentos é uma fruta?");

        bGquestao4.add(jRadioButton16);
        jRadioButton16.setText("Cenoura");

        bGquestao4.add(jRadioButton17);
        jRadioButton17.setText("Batata");

        bGquestao4.add(jRcorreta4);
        jRcorreta4.setText("Maçã");

        bGquestao4.add(jRadioButton19);
        jRadioButton19.setText("Brócolis");

        bGquestao4.add(jRadioButton20);
        jRadioButton20.setText("Feijão");

        javax.swing.GroupLayout jPquestao4Layout = new javax.swing.GroupLayout(jPquestao4);
        jPquestao4.setLayout(jPquestao4Layout);
        jPquestao4Layout.setHorizontalGroup(
            jPquestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPquestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton16)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton17)
                    .addComponent(jRcorreta4)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPquestao4Layout.setVerticalGroup(
            jPquestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRcorreta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPquestao5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("5. Qual desses instrumentos musicais é de cordas? ");

        bGquestao5.add(jRadioButton21);
        jRadioButton21.setText("Piano");

        bGquestao5.add(jRcorreta5);
        jRcorreta5.setText("Violão");

        bGquestao5.add(jRadioButton23);
        jRadioButton23.setText("Bateria");

        bGquestao5.add(jRadioButton24);
        jRadioButton24.setText("Trompete");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        bGquestao5.add(jRadioButton25);
        jRadioButton25.setText("Flauta");

        javax.swing.GroupLayout jPquestao5Layout = new javax.swing.GroupLayout(jPquestao5);
        jPquestao5.setLayout(jPquestao5Layout);
        jPquestao5Layout.setHorizontalGroup(
            jPquestao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPquestao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton21)
                    .addComponent(jRcorreta5)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPquestao5Layout.setVerticalGroup(
            jPquestao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPquestao5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRcorreta5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton25)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jBenviar.setBackground(new java.awt.Color(255, 255, 204));
        jBenviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBenviar.setForeground(new java.awt.Color(153, 51, 0));
        jBenviar.setText("Enviar");
        jBenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBenviarActionPerformed(evt);
            }
        });

        jLresultadopontos.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPquestao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPquestao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPquestao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPquestao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPquestao5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jBenviar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLresultadopontos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPquestao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPquestao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPquestao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPquestao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPquestao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBenviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLresultadopontos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBenviarActionPerformed
        if(jRcorreta1.isSelected()){
            q.setSoma(1);
        }
        else if(jRcorreta1.isSelected() && jRcorreta2.isSelected()){
            q.setSoma(1);
        }
        else if(jRcorreta1.isSelected() && jRcorreta2.isSelected() && jRcorreta3.isSelected()){
            q.setSoma(1);
        }
        else if(jRcorreta1.isSelected() && jRcorreta2.isSelected() && jRcorreta3.isSelected() && jRcorreta4.isSelected()){
            q.setSoma(1);
        }
        else if(jRcorreta1.isSelected() && jRcorreta2.isSelected() && jRcorreta3.isSelected() && jRcorreta4.isSelected() && jRcorreta5.isSelected()){
            q.setSoma(1);
        }
        else{
            jPanel2.disable();
        }

        jLresultadopontos.setText("Pontos: " + q.getSoma());
    }//GEN-LAST:event_jBenviarActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGquestao1;
    private javax.swing.ButtonGroup bGquestao2;
    private javax.swing.ButtonGroup bGquestao3;
    private javax.swing.ButtonGroup bGquestao4;
    private javax.swing.ButtonGroup bGquestao5;
    private javax.swing.JButton jBenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLresultadopontos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPquestao1;
    private javax.swing.JPanel jPquestao2;
    private javax.swing.JPanel jPquestao3;
    private javax.swing.JPanel jPquestao4;
    private javax.swing.JPanel jPquestao5;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRcorreta1;
    private javax.swing.JRadioButton jRcorreta2;
    private javax.swing.JRadioButton jRcorreta3;
    private javax.swing.JRadioButton jRcorreta4;
    private javax.swing.JRadioButton jRcorreta5;
    private javax.swing.JRadioButton jRq1a;
    private javax.swing.JRadioButton jRq1b;
    private javax.swing.JRadioButton jRq1c;
    private javax.swing.JRadioButton jRq1e;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
